server:
  port: 9090

spring:
    application:
      name: dream-eureka

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
